export {
  ContextRebuildService,
  defaultContextRebuildService,
  type TrackerBridgeConfig,
  type ExternalRef,
  type IssueCacheEntry,
  type PRCacheEntry,
  type CommentData,
  type SyncEvent,
  type LinkRole,
  type EntityLinkRequest,
  type EntityLinkResult,
  type ContextRebuildRequest,
  type RebuiltContext,
  type ConnectionStatus,
} from './context-rebuild-service.js';