@echo off
REM =============================================================================
REM shipyard-cp Environment Setup Script
REM =============================================================================
REM This script sets up the complete development environment including:
REM - Node.js dependencies
REM - Docker containers for external services
REM - Environment configuration
REM =============================================================================

setlocal enabledelayedexpansion

echo.
echo ========================================
echo  shipyard-cp Environment Setup
echo ========================================
echo.

REM Check prerequisites
echo [1/5] Checking prerequisites...

where node >nul 2>&1
if %errorlevel% neq 0 (
    echo ERROR: Node.js is not installed. Please install Node.js 20 or later.
    exit /b 1
)

where npm >nul 2>&1
if %errorlevel% neq 0 (
    echo ERROR: npm is not installed. Please install npm.
    exit /b 1
)

where docker >nul 2>&1
if %errorlevel% neq 0 (
    echo WARNING: Docker is not installed. External services will not be available.
    echo You can still run the control plane locally.
    set DOCKER_AVAILABLE=0
) else (
    set DOCKER_AVAILABLE=1
)

echo   - Node.js: OK
echo   - npm: OK
if %DOCKER_AVAILABLE%==1 (
    echo   - Docker: OK
) else (
    echo   - Docker: NOT FOUND ^(optional^)
)

REM Install Node.js dependencies
echo.
echo [2/5] Installing Node.js dependencies...
cd /d "%~dp0.."
call npm install
if %errorlevel% neq 0 (
    echo ERROR: Failed to install dependencies.
    exit /b 1
)
echo   - Dependencies installed successfully

REM Create .env file if not exists
echo.
echo [3/5] Configuring environment...
if not exist .env (
    echo Creating .env file...
    (
        echo # shipyard-cp Environment Configuration
        echo # Generated by install.bat
        echo.
        echo # Server Configuration
        echo PORT=3000
        echo NODE_ENV=development
        echo.
        echo # External Services
        echo MEMX_RESOLVER_URL=http://localhost:8080
        echo TRACKER_BRIDGE_URL=http://localhost:8081
        echo.
        echo # API Keys (set these for actual usage)
        echo GITHUB_TOKEN=
        echo OPENAI_API_KEY=
        echo ANTHROPIC_API_KEY=
        echo GOOGLE_API_KEY=
        echo GEMINI_API_KEY=
    ) > .env
    echo   - Created .env file
) else (
    echo   - .env file already exists
)

REM Build TypeScript
echo.
echo [4/5] Building TypeScript...
call npm run build
if %errorlevel% neq 0 (
    echo WARNING: Build failed. You may need to run 'npm run build' manually.
) else (
    echo   - Build completed successfully
)

REM Start Docker containers if available
if %DOCKER_AVAILABLE%==1 (
    echo.
    echo [5/5] Starting Docker containers...
    cd docker
    call docker-compose up -d
    if %errorlevel% neq 0 (
        echo WARNING: Failed to start Docker containers.
        echo You can start them manually with: cd docker ^&^& docker-compose up -d
    ) else (
        echo   - Docker containers started
        echo.
        echo Services available at:
        echo   - Control Plane:    http://localhost:3000
        echo   - memx-resolver:    http://localhost:8080
        echo   - tracker-bridge:   http://localhost:8081
    )
    cd ..
) else (
    echo.
    echo [5/5] Skipping Docker containers ^(Docker not available^)
)

echo.
echo ========================================
echo  Setup Complete!
echo ========================================
echo.
echo Next steps:
echo   1. Edit .env to configure API keys
echo   2. Run 'start.bat' to start the control plane
echo   3. Run 'npm test' to verify installation
echo.
echo For Docker services:
echo   - cd docker ^&^& docker-compose up -d
echo.
echo For development:
echo   - npm run dev     # Start with hot reload
echo   - npm test        # Run tests
echo   - npm run lint    # Run linter
echo.

pause